prefix : <http://skohub.io/skohub-shacl>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix dct: <http://purl.org/dc/terms/>



SELECT ?focusNode ?resultMessage ?value ?sourceShape ?resultPath ?sourceConstraintComponent
WHERE {
	?result a sh:ValidationResult ;
	sh:resultSeverity sh:Violation .
	?result sh:focusNode ?focusNode ;
		sh:sourceShape ?sourceShape ;
		sh:resultMessage ?resultMessage ;
		OPTIONAL { ?result sh:resultPath ?resultPath }
		OPTIONAL { ?result sh:value ?value}
}